# FROM openjdk:21-jdk-alpine
# COPY target/*.jar app.jar
# ENTRYPOINT ["java", "-jar", "/app.jar"]

# 기본 이미지는 jdk 17
FROM openjdk:21

#빌드 시점에 사용될 변수를 정의
ARG JAR_FILE=build/libs/graduationwork-0.0.1-SNAPSHOT.jar

# ARG에서 정의한 JAR_FILE 경로의 jar 파일을 컨테이너 내 app.jar로 복사
COPY ${JAR_FILE} app.jar

# 컨테이너가 시작될 때 실행될 명령어 정의
ENTRYPOINT ["java", "-jar", "app.jar"]
# ENTRYPOINT ["sh", "-c", "sleep 10 && java -jar app.jar"]
