FROM node:20

# 작업 디렉토리 설정
WORKDIR /app

# package.json과 lock 파일 복사
COPY package*.json ./

# 의존성 설치
RUN npm install

# Expo 및 ngrok 설치
RUN npm install -g expo-cli @expo/ngrok@^4.1.0

# 프로젝트 파일 복사
COPY . .

# Expo 터널 실행
CMD ["npx", "expo", "start", "--tunnel", "--port", "8082"]
